apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: apache-sqjj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: apache-sqjj
    app.kubernetes.io/part-of: apache
  name: apache-sqjj
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: apache-sqjj
status:
  loadBalancer: {}
